### ISSUE TITLE
How to install in node-red ?

### ISSUE THREAD

**Issue by titusece** [freakent/freakent-nodes#1]
Hi,

How to install this node in node-red ?
I just copied this folder into "/home/pi/.node-red/node_modules" and its not detecting.
Can you please help me on this ?

Regards,
Titus S.

**Comment by freakent** [comment]
I'm sorry, node-red has been updated a lot since I wrote these add-on modules. I believe the node-red module loading apis changed since then so that maybe why.  I'm still running a very old version of node-red on my network, one day I will get around to updating to the latest, but right now I just don't have the time.

**Comment by titusece** [comment]
That's okay, thanks for replying.
I have used the following node in latest setup where I have the latest versions of node, nodejs and node-red.
https://github.com/jankolkmeier/NR-XBeeAPI

Before that I installed the "serialport" node.

It would help someone :-)

Thanks.
